config modification
gulpjs/gulpjs.github.io pull request #131
Opened 2020-10-29 11:37 UTC by donghwipark

1. Plugins : isProd seems occuring error
2. Color mode change
3. navbar parameter naming
4. Footer title miss

2020-10-30 20:38 UTC, phated requested changes
@donghwipark when you change all the `'` to `"`, I can't tell which changes actually matter. Can you please switch those back to `'`?

2020-10-31 01:38 UTC, donghwipark commented
Oh it seems I accidently changed through prettier. Will change to " to ' and mention here which code I changed manually.

2020-10-31 01:48 UTC, donghwipark commented
I changed to single quote and seem you can check in fils changed exactly which has modified please confirm. 👍 
https://github.com/gulpjs/gulpjs.github.io/pull/131/files

2020-10-31 03:23 UTC, phated commented
Thank you for fixing that! I notice that it added commas also, but I'm those should be there anyway. I will review this and make suggestions this weekend.

2020-11-12 00:31 UTC, phated commented
@donghwipark I just noticed that you have not committed any changes to the `package.json` and `package-lock.json` files, which need to be updated for the new version of docusaurus. Did you mistakenly leave out those updates?

2020-11-12 03:46 UTC, donghwipark commented
It was a mistake, will pull request with package json

2021-01-21 04:20 UTC, phated requested changes
@donghwipark Sorry it has taken so long to review this. It looks like version `alpha.70` has been released since you submitted this PR. Can you please update and apply any changes needed for that new version?

2021-01-21 04:20 UTC, phated commented on docusaurus.config.js
> +    ['@docusaurus/plugin-sitemap', {}],
Version `alpha.68` and higher fixed this issue (with https://github.com/facebook/docusaurus/pull/3704), so we can add these back.
```suggestion
    isProd && ['@docusaurus/plugin-google-analytics', {}],
    isProd && ['@docusaurus/plugin-google-gtag', {}],
    isProd && ['@docusaurus/plugin-sitemap', {}],
```

2021-01-23 19:14 UTC, phated commented
@donghwipark it looks like you pulled/merged master instead of the `source` branch 😬

2021-01-24 06:07 UTC, closed without merging

2021-01-25 04:51 UTC, donghwipark commented
Yes I accidently pulled the master.. I pull request with another commit please confirm.