Docusaurus upgrade debugging
gulpjs/gulpjs.github.io pull request #133
Opened 2021-01-24 06:05 UTC by donghwipark

1. docusaurus-plugin-sass"from  0.1.08 to 0.1.11
2. config modification
3. Implement Navbar/index.js accordingly

2021-01-27 19:47 UTC, phated requested changes
I reviewed the site and found a bunch of issues that need to be fixed. I will comment on the PR thread.

2021-01-27 19:47 UTC, phated commented on docusaurus.config.js
> +      disableSwitch: false,
```suggestion
      disableSwitch: true,
```

This should be true, as our theme doesn't work with dark mode.

2021-01-27 19:50 UTC, phated commented
The algolia search box changed and needs styling updates to match our search box:

The changes make it look like this:
<img width="238" alt="Screen Shot 2021-01-27 at 12 40 21 PM" src="https://user-images.githubusercontent.com/992373/106045258-f4e96300-609d-11eb-8ace-d5746b7ad9e6.png">

But it should look like this:
<img width="222" alt="Screen Shot 2021-01-27 at 12 43 09 PM" src="https://user-images.githubusercontent.com/992373/106045320-029ee880-609e-11eb-8a08-ed5b2f45a3e7.png">

And on mobile:
<img width="353" alt="Screen Shot 2021-01-27 at 12 49 12 PM" src="https://user-images.githubusercontent.com/992373/106045370-134f5e80-609e-11eb-9955-62373d9d0e4c.png">

But should look like:
<img width="371" alt="Screen Shot 2021-01-27 at 12 46 53 PM" src="https://user-images.githubusercontent.com/992373/106045400-1ba79980-609e-11eb-8bd3-50c5b3b123f1.png">

I'm okay adjusting to to a dark-background search icon for mobile, but it would need to come with additional navbar updates to make things look proportionate.

2021-01-27 19:51 UTC, phated commented
The word "logo" appears in the footer for some reason now:

<img width="386" alt="Screen Shot 2021-01-27 at 12 46 09 PM" src="https://user-images.githubusercontent.com/992373/106045557-5578a000-609e-11eb-9934-e3c360f1af4f.png">

2021-01-27 19:52 UTC, phated commented
The plugins page keyword lists got messed up:
<img width="974" alt="Screen Shot 2021-01-27 at 12 45 41 PM" src="https://user-images.githubusercontent.com/992373/106045630-717c4180-609e-11eb-812b-0f241bc203cb.png">
<img width="979" alt="Screen Shot 2021-01-27 at 12 45 47 PM" src="https://user-images.githubusercontent.com/992373/106045633-72ad6e80-609e-11eb-8077-ec43491a31c5.png">

I assume this was a change with the underlying css library that we use from docusaurus

2021-01-27 19:53 UTC, phated commented
We should also remove this patch https://github.com/gulpjs/gulpjs.github.io/pull/130 that was put into place to fix an issue until we upgraded past alpha.66

2021-01-27 19:54 UTC, phated commented
@donghwipark let me know once you've completed those fixes and I will review again.

2021-02-23 07:16 UTC, donghwipark commented
@phated I fixed the issues you mentioned above. Please confirm.

2021-04-07 00:31 UTC, phated reviewed
@donghwipark great work on this! I have some cleanup that I'm going to push then I'll merge!

2021-04-07 00:31 UTC, phated commented on src/css/docs.css
> +}
There's a bunch of issues here, but I'm just going to push a fix.

2021-04-07 00:31 UTC, phated commented on src/css/docs.css
> +  }
Same as above. Also, you added code instead of replacing the navbar__search stuff,

2021-04-07 00:31 UTC, phated commented on src/css/docs.css
>  }
This was supposed to be removed as I mentioned. Will push the update.

2021-04-07 00:31 UTC, phated commented on src/theme/Navbar/index.js
> +// import Toggle from '@theme/Toggle';
Why was this code commented out? Just delete it if that's your solution. I'll push the fix.

2021-04-07 00:31 UTC, phated commented on src/theme/Navbar/index.js
> +  // );
Same, and you should have cleaned up the other code that used these values. I'll push.

2021-04-07 00:31 UTC, phated commented on src/theme/Navbar/index.js
> +          )} */}
Same as above. Don't comment code, just delete it. I'll push.

2021-04-07 00:31 UTC, phated commented on src/css/docs.css
> +}
Specifically, you should have been using the css variables and reviewing the different states, hover/active/etc.

2021-04-07 00:38 UTC, merged